apiVersion: apps/v1
kind: Deployment
metadata:
  name: letter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letter
  template:
    metadata:
      labels:
        app: letter
    spec:
      containers:
        - name: letter
          image: ellieene/letter:latest
          ports:
            - containerPort: 8002
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092